language: php
dist: trusty
sudo: false

php:
  - 7.0

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  global:
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
    - SYMFONY_DEPRECATIONS_HELPER=disabled
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable
    - RELEASE=stable COMPOSER_CHANNEL=snapshot

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose validate
  - composer --verbose install
  - composer global require consolidation/cgr
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - cgr drush/drush:8.1.15

script:
  - cd $TRAVIS_BUILD_DIR/web
  - drush site-install config_installer config_installer_sync_configure_form.sync_directory=../config/sync --verbose --yes --db-url=mysql://root:@localhost/drupal
  - drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
  # Ignore Setup group temporarily, @see https://www.drupal.org/node/2962157
  # Ignore webform tests temporarily. TODO: try to newer version of webform and remove again
  # Ignore redirect because of failing tests. TODO Update and try again
  # Ignore features because of failing tests. TODO Update and try again
  - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache,Setup,webform,redirect,features
  - drush
  - if [[ $RELEASE = stable ]]; then ./../vendor/bin/drupal; fi;
